apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-image-deploy
  name: java-image-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-image-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-image-deploy
    spec:
      containers:
      - image: selmi1999/java-image:latest
        name: java-image
        resources: {}
status: {}
