apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-image-deploy
  name: java-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-image-deploy
status:
  loadBalancer: {}
